_BASE_: '../detr_base.yaml'

MODEL:
  META_ARCHITECTURE: "DeformableDetr"
  WEIGHTS: "./checkpoints/r50_deformable_detr-checkpoint.pth"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: False
  
  DETR:
    NUM_CLASSES: 98
    DEC_N_POINTS: 4
    ENC_N_POINTS: 4
    NHEADS: 8
    TWO_STAGE: False
    NUM_FEATURE_LEVELS: 4
    HIDDEN_DIM: 256
    DIM_FEEDFORWARD: 1024
    DROPOUT: 0.1
    NUM_OBJECT_QUERIES: 100


SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.0003
  BASE_LR_END: 0.00000001
  MAX_ITER: 60000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 5000
  LR_SCHEDULER_NAME: WarmupCosineLR
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True

INPUT:
  DEP_GRAPH: False